// h5s/h5-react-ts/src/pages/Home.tsx
import { useState } from 'react'

export default function Home() {
  const [count, setCount] = useState(0)
  return (
    <div>
      <h1 style={{ color: '#61dafb' }}>🏠 Home (React 19)</h1>
      <p>这是首页。路由:<code>/</code></p>
      <button
        onClick={() => setCount(c => c + 1)}
        style={{
          padding: '12px 24px',
          background: '#61dafb',
          color: 'white',
          border: 'none',
          borderRadius: 6,
          fontSize: 16,
          cursor: 'pointer',
        }}
      >
        点击了 {count} 次
      </button>
    </div>
  )
}

// h5s/h5-vue-ts/src/pages/Home.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div>
    <h1>🏠 Home (Vue 3)</h1>
    <p>这是首页。路由:<code>/</code></p>
    <button class="btn" @click="count++">点击了 {{ count }} 次</button>
  </div>
</template>

<style scoped>
.btn {
  padding: 12px 24px;
  background: #42b883;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 16px;
  cursor: pointer;
}
.btn:hover { background: #369870; }
code { background: #f5f5f5; padding: 2px 6px; border-radius: 4px; }
</style>
